[project]
name = "dlt-duckdb-phish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.35.57",
    "dlt[duckdb,parquet]>=1.3.0",
    "duckdb>=1.1.3",
    "polars>=1.12.0",
]
